name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --all --check
    - name: Lint with clippy
      run: cargo clippy --all-targets -- -D warnings
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install openssl
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
    - name: Run integration tests
      env:
        DIGITRANSIT_API_KEY: ${{ secrets.digitransit_api_key }}
        DATABASE: bikes.db
        PORT: 3000 # not used but required by conf
      run: |
        # do migrations
        for sql in migrations/*; do
          sqlite3 ${DATABASE} < $sql
        done
        DATABASE_URL=sqlite:${DATABASE} cargo test -- --include-ignored
